-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        inactive_timeout = 20.0,
    },
    decoration = {
        blur = {
            noise = 0.05,
            passes = 2,
            size = 2,
        },
        dim_inactive = true,
        dim_strength = 0.3,
        inactive_opacity = 0.9,
        rounding = 7,
    },
    dwindle = {
        force_split = 2,
        preserve_split = true,
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        allow_tearing = true,
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(ffffffff)", "rgba(ffffffff)"},
                angle = 45,
            },
            inactive_border = "0xff000000",
        },
        gaps_in = 2,
        gaps_out = 4,
        snap = {
            enabled = true,
        },
    },
    misc = {
        vrr = 1,
    },
})

-- Bezier curves
hl.curve("easeInCubic", { type = "bezier", points = { {0.32, 0.0}, {0.67, 0.0} } })
hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1.0}, {0.32, 1.0} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2.0,
    bezier = "easeInCubic",
    style = "slide",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "easeOutQuint",
    style = "slide",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "easeInCubic",
    style = "slide",
})

-- Keybinds
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen())
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.layout("togglesplit"))
